services:
  postgres:
    image: postgres:17-alpine
    container_name: evently-postgres
    environment:
      POSTGRES_USER: evently
      POSTGRES_PASSWORD: evently
      POSTGRES_DB: evently
    ports:
      - '5432:5432'
    volumes:
      - evently-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U evently -d evently']
      interval: 2s
      timeout: 2s
      retries: 15

volumes:
  evently-pgdata:
