import { pgTable, serial, text } from 'drizzle-orm/pg-core'

// Auth tables (user, session, account, verification) are generated by the
// better-auth CLI (`npx @better-auth/cli generate`) and owned by better-auth.
export * from './auth-schema'

export const categories = pgTable('categories', {
  id: serial('id').primaryKey(),
  name: text('name').notNull().unique(),
})
